apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- namespace.yaml
- apps.yaml

patches:
  - target:      
      version: v1
      kind: ServiceAccount
      name: source-controller
      namespace: flux-system
    path: wi.yaml